### ISSUE TITLE
yaml vs yml

### ISSUE THREAD

**Issue by MarkEdmondson1234** [hadley/pkgdown#176]
If I use a configuration file that is named `_pkgdown.yaml` then the reference rules aren't applied to the functions to reorder them etc.

```yaml
reference:
  - title: "Authentication"
    desc: >
      Authentication with Google
    contents: 
      - ga_auth
      - authDropdownUI
```

If I rename it to `_pkgdown.yml` (after ignoring the warning RStudio gives me that I should call them `yaml`) then it works as expected.
