### ISSUE TITLE
avoid truncation of long function names

### ISSUE THREAD

**Issue by jefferis** [hadley/pkgdown#183]
Truncated function names:

![image](https://cloud.githubusercontent.com/assets/23763/19515648/3abc930c-95f0-11e6-844b-b7c29e0ff0c4.png)

**Comment by jefferis** [comment]
After playing with `pkgdown.css`. Any automated way to handle this? Somewhat related to #160

```css
/* spacing of functions */
.dl-horizontal dt {
  white-space: normal;
  width: 33%;
}

.dl-horizontal dd {
  margin-left: 35%;
}
```

![image](https://cloud.githubusercontent.com/assets/23763/19515726/8480cbf2-95f0-11e6-880b-44c9e91dfefd.png)
