### ISSUE TITLE
Section anchors (to make linking easier)

### ISSUE THREAD

**Issue by hadley** [hadley/pkgdown#192]
```css
.hasAnchor {
  margin-left: -30px;
}

a.anchor {
  display:inline-block;
  width: 30px;
  height: 30px;
  visibility: hidden;

  background-image: url(./images/link.svg);
  background-repeat: no-repeat;
  background-size: 20px 20px;
  background-position: center center;
}

.hasAnchor:hover a.anchor {
  visibility: visible;
}
```

Then for each section with an `id` attribute, find first heading (h1, h2, or h3),  insert:

```R
<a class='anchor' href='#id'></a>
```

Also need to supply appropriate option to pandoc to ensure that all sections get an id.
