### ISSUE TITLE
Suggestion: check that contents section of _pkgdown.yml is valid 

### ISSUE THREAD

**Issue by jamesdunham** [hadley/pkgdown#236]
pkgdown does some handling of missing keys in `_pkgdown.yml`, for example giving `Warning: Section must have components 'title', 'contents'` if either of these is missing from the reference section. It ignores arbitrary, unused keys. 

I don't think pkgdown checks the validity of the `contents` list in the reference block before evaluating it, but doing this might help users avoid mistakes. I just tried to use `contains()` for string matching, remembering that `starts_with()` and `ends_with()` could be used and thinking of dplyr, when I should've used `matches()`. The result of building the site was `Error in .p(.x[[i]], ...) : could not find function "f"`. It wasn't immediately clear that this was a `_pkgdown.yml` issue, or where exactly the problem was; catching the error earlier could be helpful.

```
reference:
  - title: Some title
    desc: Some description
    contents:
      - contains("some text")
```
