### ISSUE TITLE
Error: Must be all negative or all positive

### ISSUE THREAD

**Issue by topepo** [hadley/pkgdown#293]
`pkgdown` is having issues generating the reference pages for [`recipes`](https://github.com/topepo/recipes) (v 0.0.1.9000). This worked prior to the most recent update. The error is
```r
> library(pkgdown)
> build_site()
Initialising site -------------------------------------------------------------
Copying '/Users/max/Library/R/3.3/library/pkgdown/assets/jquery.sticky-kit.min.js'
Copying '/Users/max/Library/R/3.3/library/pkgdown/assets/link.svg'
Copying '/Users/max/Library/R/3.3/library/pkgdown/assets/pkgdown.css'
Copying '/Users/max/Library/R/3.3/library/pkgdown/assets/pkgdown.js'
Building home -----------------------------------------------------------------
Updating README.md
Building article 'index.html'
Building function reference ---------------------------------------------------
Error: Must be all negative or all positive
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.3

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pkgdown_0.1.0.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10       knitr_1.15.1       xml2_1.1.1         whisker_0.3-2     
 [5] magrittr_1.5       roxygen2_6.0.1     pkgload_0.0.0.9000 R6_2.2.0          
 [9] stringr_1.2.0      tools_3.3.2        withr_1.0.2        htmltools_0.3.5   
[13] commonmark_1.2     yaml_2.1.14        lazyeval_0.2.0     assertthat_0.1    
[17] rprojroot_1.2      digest_0.6.12      tibble_1.2         crayon_1.3.2      
[21] purrr_0.2.2        callr_1.0.0.9000   evaluate_0.10      rmarkdown_1.3.9004
[25] stringi_1.1.2      desc_1.1.0         backports_1.0.5   
```
The issue seems to be in `select_topics`, perhaps from trouble with the regular expressions in `_pkgdown.yml`:
```yml
template:
  params:
    bootswatch: united

reference:
  - title: Basic Functions
    contents:
    - matches("(learn)|(recipe)|(selection)|(^is)|(has_role)")
    - init_site
  - title: Example Datasets
    contents:
    - matches("(okc)|(biomass)|(credit)")
    - init_site    
  - title: Step Functions
    contents:
    - matches("step_")
    - init_site


navbar:
  left:
  - text: Simple Example 
    href: articles/1_Simple_Example.html   
  - text: Selecting Variables
    href: articles/2_Selecting_Variables.html     
  - text: Custom Steps
    href: articles/3_Custom_Steps.html
  - text: Reference
    href: reference/index.html
```
