### ISSUE TITLE
docs/reference/index.html file for dataset packages

### ISSUE THREAD

**Issue by davebraze** [hadley/pkgdown#299]
I am wanting to use pkgdown to document a dataset only package (cf. "R Packages" book pp 93). But the title and H1 header in docs/reference/index.html default to "Function reference". 

Is there a way to modify the title and H1 header via the _pkgdown.yml file to something less specific, like "Reference" or "Object reference"?

The package in question is here: [https://github.com/davebraze/FDBwordsets](https://github.com/davebraze/FDBwordsets).

**Comment by yiluheihei** [comment]
Function reference is specified in the [reference index template](https://github.com/hadley/pkgdown/blob/master/inst/templates/content-reference-index.html#L4), and there is no configuration option for it in `_pkgdown.yml`.

**Comment by davebraze** [comment]
I see now. It would be a nice addition, but obviously not the highest priority. Thanks to all contributors for your work on this very useful package.

**Comment by hadley** [comment]
I think we could just change the title in the template for all packages

**Comment by yiluheihei** [comment]
just separate the data and function reference？

like:

```yaml
Reference
  - title: Data Reference
    - subtitle1: 
      - desc
      - contents：
    - subtitle2:
      - desc
      - contents：
  - title: Function Reference
    - subtitle1:
      - desc
      - contents：
    - subtitle2:
      - desc
      - contents：
```

# Reference
#### package version
---------------
## Data reference
###  subtitle1 
desc
contents
###  subtitle2
desc
contents
## Function reference
###  subtitle1 
desc
contents
###  subtitle2
desc
contents
