### ISSUE TITLE
Help topic with-a-hyphen is problematic

### ISSUE THREAD

**Issue by jennybc** [hadley/pkgdown#309]
It is tricky to work with a help topic that contains a hyphen in `_pkgdown.yml`.

I've got one called `cell-specification` in readxl. It appears in a context like so:

```xml

  - title: "Describe a target rectangle"
    desc: >
      Flexible specification of cell rectangles.
    contents:
      - cell-specification
      - cell_rows
      - cell_cols
      - anchored
      - cell_limits
```

The above generates this error:

```
Building function reference -----------------------------------------------------
Error in eval(expr, envir, enclos) : object 'cell' not found
```

If I quote with backticks, I get this error:

```
Error in yaml.load(paste(readLines(input, encoding = "UTF-8"), collapse = "\n"),  : 
  Scanner error: while scanning for the next token at line 28, column 9found character that cannot start any token at line 28, column 9
```

If I quote with double quotes, I get the first error again.

If I quote with double quotes and, inside, backticks, that works!

```
  - title: "Describe a target rectangle"
    desc: >
      Flexible specification of cell rectangles.
    contents:
      - "`cell-specification`"
```

**Comment by hadley** [comment]
I think the best I can do (without a lot of work) would be to provide a helper so you could do:

```yaml
  - title: "Describe a target rectangle"
    desc: >
      Flexible specification of cell rectangles.
    contents:
      - one_of("cell-specification")
```
