### ISSUE TITLE
has_vignette doesn't use article order specified in _pkgdown.yml

### ISSUE THREAD

**Issue by jkennel** [hadley/pkgdown#325]
When I specifically define articles in _pkgdown.yml the article order is not preserved in the output .html (due to has_vignette using %in%). Is this the desired effect?

```yaml
articles:
  - title: "topic 1"
    desc: >
      description 1
    contents:
    - article_d
    - article_a
    - article_b
    - article_c
- title: "topic 2"
    desc: >
      description 2
    contents:
    - article_h
    - article_f
    - article_e
    - article_g
```
