### ISSUE TITLE
authors setting doesn't seem to work

### ISSUE THREAD

**Issue by zbjornson** [hadley/pkgdown#345]
From the docs:

> You can also provided information to override the default display of the authors. Provided a list named with the name of each author, including href to add a link, or html to override the text:
>```
> authors:
>  Hadley Wickham:
>    href: http://hadley.nz
> ```

I'm either using it wrong, or it doesn't seem to work. I've set it as a top-level setting in _pkgdown.yml, but the site only reflects what's in DESCRIPTION.

Thanks for yet another nice package!

**Comment by yiluheihei** [comment]
IMO, the author name must in the `Authors@R` section of the package `DESCRIPTION` file.

**Comment by zbjornson** [comment]
That's fine if that's the intended behavior; then it should be removed from the documentation.

**Comment by yiluheihei** [comment]
I don't thinks so.  By default, `pkgdown` query and  display authors in Authors@R in DESCRIPTION.  You can override the default display of the authors by configuring the `authors` metadata in `_pkgdown.yml`.

```
authors:
  <author_name_to_modify, must in Authors@R>: 
    html: <the desired author name you want to display, will replace "author_name_to_modify">
    href: <add href link to this author, e.g. author's website>
```
